New challenge added
perifacode/conteudo-gratuito pull request #153
Opened 2020-10-05 20:09 UTC by andyantunes

Adicionado um novo link de desafio de JavaScript. [JavaScript30](https://javascript30.com/)

2020-10-05 21:02 UTC, gitlherme requested changes
@andyantunes estão ocorrendo alguns conflitos no documento. Você pode dar uma olhada?

2020-10-05 23:12 UTC, andyantunes commented
Ok, vou verificar.

2020-10-05 23:28 UTC, andyantunes commented
Conflitos resolvidos.

2020-10-06 13:49 UTC, merged

2020-10-06 13:50 UTC, gitlherme commented
@all-contributors please add @andyantunes for content

2020-10-06 13:50 UTC, gitlherme commented
Valeu pelo PR, @andyantunes 💛